# Generated by Django 4.0 on 2022-02-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_blog_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='blog_image',
        ),
        migrations.AddField(
            model_name='post',
            name='blogimage',
            field=models.ImageField(blank=True, upload_to='blog_image'),
        ),
    ]
