# Generated by Django 4.0 on 2022-02-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_blogimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blogimage',
            field=models.ImageField(upload_to='blog_image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
